import Head from 'next/head';
import { useEffect, useState } from 'react';
import Card from '../components/Card';
import Input from '../components/Input';
import { myMovies, userMovies } from '../utils/data';

export default function Home() {
	const [currentAccount, setCurrentAccount] = useState('');

	const checkIfWalletIsConnected = async () => {
		try {
			const { ethereum } = window;

			if (!ethereum) {
				console.log('Make sure you have metamask!');
				return;
			} else {
				console.log('We have the ethereum object', ethereum);
			}

			const accounts = await ethereum.request({ method: 'eth_accounts' });

			if (accounts.length !== 0) {
				const account = accounts[0];
				console.log('Found an authorized account:', account);
				setCurrentAccount(account);
			} else {
				console.log('No authorized account found');
			}
		} catch (error) {
			console.log(error);
		}
	};

	/**
	 * Implement your connectWallet method here
	 */
	const connectWallet = async () => {
		try {
			const { ethereum } = window;

			if (!ethereum) {
				alert('Get MetaMask!');
				return;
			}

			const accounts = await ethereum.request({ method: 'eth_requestAccounts' });

			console.log('Connected', accounts[0]);
			setCurrentAccount(accounts[0]);
		} catch (error) {
			console.log(error);
		}
	};

	useEffect(() => {
		checkIfWalletIsConnected();
	}, []);

	const myFavorites = myMovies.map((movie, index) => <Card key={index} movie={movie} />);
	const userFavorites = userMovies.map((movie, index) => <Card key={index} movie={movie} />);

	return (
		<div className='bg-gradient-to-br from-purple-700 via-indigo-800 to-indigo-900'>
			<Head>
				<title>Film Waves</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='container mx-auto'>
				<div className='flex flex-wrap items-start pt-6 px-6'>
					<div className='flex-initial lg:flex-1'>
						<article>
							<h1>Hi! I&apos;m Nitegeist ☄️</h1>
							<p>
								I&apos;m a Software Developer with a keen interest in movies. I have a particular love for
								action/fighting films. Here are two of my favorites, now send me yours!
							</p>
						</article>
						<div className='relative flex items-center pt-10 pr-8'>
							{!currentAccount ? (
								<button type='button' onClick={connectWallet} className='connect-btn'>
									Connect Wallet
								</button>
							) : (
								<Input account={currentAccount} />
							)}
						</div>
					</div>
					<div className='flex-initial lg:flex-1'>
						<div className='flex flex-wrap items-center justify-center pt-10 lg:pt-0'>{myFavorites}</div>
					</div>
				</div>
				<div className='pt-10 px-6'>
					<p className='font-semibold'>User Recommendations &rarr;</p>
					<div className='flex flex-wrap items-center justify-center md:justify-start'>{userFavorites}</div>
				</div>
			</main>
			<footer className='p-12 text-center'>
				<p className='text-sm text-white text-opacity-70'>&copy; {new Date().getFullYear()} Made by Nitegeist</p>
			</footer>
		</div>
	);
}
