import Head from 'next/head';
import Card from '../components/Card';
import Input from '../components/Input';
import { myMovies, userMovies } from '../utils/data';

export default function Home() {
	// const [connected, setConnected] = useState(false);
	// // request access to the user's MetaMask account
	// const requestAccount = async () => {
	// 	await window.ethereum
	// 		.request({ method: 'eth_accounts' })
	// 		.catch((err) => console.log(err));
	// };

	// const connectWallet = async () => {
	// 	if (typeof window.ethereum !== 'undefined') {
	// 		await requestAccount().then(() => setConnected(true));
	// 	}
	// };

	// useEffect(() => {
	// 	if (typeof window.ethereum !== 'undefined') {
	// 		window.ethereum.isConnected() ? setConnected(true) : setConnected(false);
	// 	}
	// }, []);

	const myFavorites = myMovies.map((movie, index) => (
		<Card key={index} movie={movie} />
	));
	const userFavorites = userMovies.map((movie, index) => (
		<Card key={index} movie={movie} />
	));

	return (
		<div className='bg-gradient-to-br from-purple-700 via-indigo-800 to-indigo-900'>
			<Head>
				<title>Blockchainbuster</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className='container mx-auto'>
				<div className='flex flex-wrap items-start pt-6 px-6'>
					<div className='flex-initial lg:flex-1'>
						<article>
							<h1>Hi! I&apos;m Nitegeist ☄️</h1>
							<p>
								I&apos;m a Software Developer with a keen interest in movies. I
								have a particular love for action/fighting films. Here are two
								of my favorites, now send me yours!
							</p>
						</article>
						<div className='relative flex items-center pt-10 pr-8'>
							{/* {!connected ? (
								<button
									type='button'
									onClick={connectWallet}
									className='connect-btn'>
									Connect Wallet
								</button>
							) : ( */}
							<Input />
						</div>
					</div>
					<div className='flex-initial lg:flex-1'>
						<div className='flex flex-wrap items-center justify-center pt-10 lg:pt-0'>
							{myFavorites}
						</div>
					</div>
				</div>
				<div className='pt-10 px-6'>
					<p className='font-semibold'>User Recommendations &rarr;</p>
					<div className='flex flex-wrap items-center justify-center md:justify-start'>
						{userFavorites}
					</div>
				</div>
			</main>
			<footer className='p-12 text-center'>
				<p className='text-sm text-white text-opacity-70'>
					&copy; {new Date().getFullYear()} Made by Nitegeist
				</p>
			</footer>
		</div>
	);
}
